### ISSUE TITLE
Support S3 Server-Side-Encryption

### ISSUE THREAD

**Issue by jhmartin** [thenickdude/snap-to-s3#1]
Please consider supporting S3 ServerSideEncryption, minimally the AES256 mode and possibly the KMS mode: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createMultipartUpload-property particularly the ServerSideEncryption and SSEKMSID properties.

**Comment by thenickdude** [comment]
I've now added support for AES256 and aws:kms, which appears to work for me. Please let me know if this works for you.
