### ISSUE TITLE
Not all illegal characters are replaced when creating snapshot

### ISSUE THREAD

**Issue by dsl101** [thenickdude/snap-to-s3#15]
Only just started using snap-to-s3, so perhaps this is user error, but several of my snapshots have the '/' character in the Description, and this seems to be used for the object name in S3, causing 'folders' to be created. Here's an example of what I see in the 'breadcrumbs' on the S3 console:

![image](https://user-images.githubusercontent.com/900542/103410783-c93d9080-4b64-11eb-9c26-49226687bfcd.png)

Is that right?

**Comment by thenickdude** [comment]
Folders are effectively a fiction of the web client, they don't actually exist as far as S3 is concerned and everything will continue to work fine.
