### ISSUE TITLE
Option for flat tar no compression

### ISSUE THREAD

**Issue by orcutt989** [thenickdude/snap-to-s3#18]
Could we add an option for no compression? flat tar?

**Comment by thenickdude** [comment]
With the default compression level of 1 it should be extremely lightweight with either zstd or lz4. Do you need to be able to seek within the tar or something?

**Comment by orcutt989** [comment]
Wow thanks for the fast reply. No seeking, just curious about the difference between lz4 level 1 and uncompressed. Seems trivial but I just wanted to confirm.

**Comment by thenickdude** [comment]
It's crazy fast, to the point that disabling it will make performance worse for just about all usecases

**Comment by orcutt989** [comment]
Awesome thanks
