### ISSUE TITLE
snap-to-s3 error : Missing required utility 'lsblk', is it on the path? 

### ISSUE THREAD

**Issue by abhaykrp** [thenickdude/snap-to-s3#2]
I am trying to use snap-to-s3 for backup the ebs snapshot when I try to use following command it fails and give the following error :

bash-3.2$ sudo snap-to-s3 --migrate --all --bucket <bucket name>.s3.amazonaws.com
Error: Missing required utility 'lsblk', is it on the path? 

Terminating due to fatal errors.
bash-3.2$ 

Can someone help please?

**Comment by thenickdude** [comment]
Which operating system?

**Comment by QuentinDela** [comment]
Hey @thenickdude , 
I have the same issue. 
I am on MacOS.
Thanks for your help.

**Comment by thenickdude** [comment]
Snap-to-s3 must be run on an EC2 instance, not on your desktop. If you did run it in EC2, which operating system is  on that machine?
